# Generated by Django 5.0.7 on 2024-07-22 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_service',
            field=models.CharField(blank=True, choices=[('payme', 'Payme'), ('click', 'Click'), ('apelsin', 'Apelsin'), ('paynet', 'Paynet'), ('octo', 'Octo'), ('payze', 'Payze'), ('uzum', 'Uzum'), ('alif', 'Alif'), ('atmos', 'Atmos')], max_length=10, null=True, verbose_name='Платежная служба'),
        ),
        migrations.CreateModel(
            name='CardToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
